# Generated by Django 2.1.3 on 2019-11-07 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0008_auto_20191028_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='read_date',
            field=models.DateField(default=datetime.date(2019, 11, 7)),
        ),
    ]
