# Generated by Django 2.1.3 on 2019-10-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeNum',
            new_name='LikeCount',
        ),
    ]
